### PR TITLE
Add Cocoa Dock icon progress bar implemenetation

### PR DESCRIPTION
**Pull request by ws909**
Tested this with a single window, and that worked fine, but I was unable to test it with multiple windows. That would require changing the `window` test program to allow for multiple windows, which wasn't as straightforward.

### CODE REVIEW

**Comment by ws909** [comment]
@GamesTrap 
Created a PR now.[^1]

[^1]: Didn't seem like you're monitoring your own fork's repository, so I thought I'd ping you. I missed a PR in my fork's repository for 2 weeks because of that.

**Comment by GamesTrap** [comment]
@ws909 Thanks for the ping, you were right.

Please fix the macOS build errors.

Will merge this after the GitHub Action workflows pass and I retested the code on Windows 11 & Kubuntu 22.10.

**Comment by ws909** [comment]
Such a beginner mistake on my part.

@GamesTrap Fixed.

**Comment by GamesTrap** [comment]
Should we also emit an error when this functionality gets used on a macOS version which doesnt support the NSProgressIndicator class?

This is currently done on Windows when used on Windows Vista or older:

```c
if(!IsWindows7OrGreater())
{
    _glfwInputError(GLFW_FEATURE_UNAVAILABLE, "Win32: Taskbar progress is only supported on Windows 7 or newer");
    return;
}
```

or should we simply return in this case instead?

**Comment by ws909** [comment]
NSProgressIndicator is supported on all versions of MacOS that GLFW supports.

**Comment by ws909** [comment]
It's been a part of Cocoa since OS X 10.0; 23 years ago.

**Comment by ws909** [comment]
Oh, woops. Don't merge my PR. I shouldn't have used a "@" in the commit message. Will change that.

**Comment by ws909** [comment]
@GamesTrap Ready to merge.

**Comment by GamesTrap** [comment]
@ws909 Are you sure? I can still see the `Enclose [indicator setControlSize] in if @available 8d3b3bf` commit in the history.

**Comment by ws909** [comment]
Ah.
```
git reset --hard HEAD~1
git commit --amend
git pull
git push -f
```
It's probably that pull I did which added it back in.

[Next step]: climb into time machine, warn myself not to use "@" in commit messages, then proceed.

**Comment by ws909** [comment]
Well, the time machine wouldn't start up, so I did it the ugly way.

**Comment by GamesTrap** [comment]
Works on Windows 11 and Kubuntu 22.10 x86_64 6.1.9-060109-generic

Merging now

**Comment by ws909** [comment]
Just spotted a typo which I fixed and pushed an extra commit for. You shouldn't need to rerun the tests for this.

**Pull request merged**
